pipeline{
    agent any

    stages{
        stage('Build') {
            steps {
                git 'https://github.com/PhongNguyen520/Jenkins.git'
            }
        }

        stage('PushDocker') {
            steps {
                // Use the default Docker Hub registry URL (optional)
                withDockerRegistry(credentialsId: 'docker-hub', url: 'https://index.docker.io/v1/') {
                    sh 'docker build -t aspnetcoretest .'
                    sh 'docker push aspnetcoretest'
                }
            }
        }
    }
}
