pipeline{
    agent any
    stages{
        stage('Build'){
            steps {
                 git 'https://github.com/PhongNguyen520/Jenkins.git'
            }
        }

        stage('PushDocker'){
            steps {
                withDockerRegistry(credentialsId: 'docker-hub', url: 'https://index.docker.io/v1/') {
                    sh 'docker build -t aspnetcore-test .'
                    sh 'docker push aspnetcore-test'
                }
            }
        }

    }
}